services:
  db:
    image: pgvector/pgvector:pg16
    restart: always
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: my_authentication_db
    volumes:
      - pgdata:/var/lib/postgresql/data

  embedding-service:
    build: ./embedding-service
    restart: always
    ports:
      - "8001:8000"
    environment:
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  pgdata: