services:
  db:
    image: pgvector/pgvector:pg16
    restart: always
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: my_authentication_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: